# Variable setup.
# load all variables
- name: Load all variable files from defaults
  ansible.builtin.include_vars:
    dir: ../defaults
    extensions:
      - yml

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Include OS-specific task.
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
