---
- name: Configure php-fpm pools
  template:
    src: "{{ item.pool_template }}"
    dest: "{{php_fpm_pool_conf_dir}}/{{ item.pool_name }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ php_fpm_pools }}"
  notify: restart php-fpm